# Generated by Django 5.0.2 on 2024-02-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_book_price_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='imagen',
            field=models.TextField(default='default.jpg'),
            preserve_default=False,
        ),
    ]
